#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

ynh_script_progression "Backing up MCP SSH Manager..."

ynh_backup "$install_dir"
ynh_backup "$data_dir"
ynh_backup "$sudoers_file"
ynh_backup "$log_dir"
