#!/bin/bash
source _common.sh
source /usr/share/yunohost/helpers

ynh_app_setting_set --key=approver --value="$approver"
ynh_script_progression "Installing the minimal MCP server..." --weight=10
install_application_files

ynh_script_progression "Configuring loopback SSH and sudo..." --weight=3
configure_internal_ssh
configure_privileges

ynh_script_progression "Configuring HTTPS, OAuth and the approval interface..." --weight=5
ynh_permission_update --permission=main --add="$approver"
configure_runtime

ynh_script_progression "Testing the MCP service..." --weight=2
self_test
ynh_script_progression "Installation of $app completed" --last
